### ISSUE TITLE
'lpath' not correctly used when downloading

### ISSUE THREAD

**Issue by masangster** [Azure/azure-data-lake-store-python#215]
### Description
The 'lpath' argument passed to the downloader does not get used reliably when downloading. 

---

### Reproduction Steps
Try different forms of the 'lpath' argument when downloading a directory - sometimes the download location path is taken relative to where the python script that called it is located, sometimes it is taken relative to the local root eg. C:/, and the actual 'lpath' naming is not used reliably, i.e. if I am downloading /root/path/files to an 'lpath' of /testpath/test, I do not end up with testpath/test/files/... . Sometimes I get testpath/files/..., and sometimes the files/... download directly into the location of the python script that called the downloader. 

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
0.0.19

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
3.6.2 64 bit

**OS Version:** What OS and version are you using?  
Windows 7 Enterprise 64-bit

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Python via VS Code

**Comment by masangster** [comment]
Any progress on investigating this MS? As a large enterprise customer it is critical that data lake data transfer is rock solid and this currently prevents us from moving forward with the roll out of data lake as a storage solution.

**Comment by milanchandna** [comment]
Looking into it.

**Comment by camronkhan** [comment]
When I specify a file path for _lpath_ it works correctly.  But when I specify a directory path (i.e., downloading a directory of files) then it seems to use _rpath_ as the target path.

**Comment by camronkhan** [comment]
I believe the root cause occurs at [line 199 in multithread.py](https://github.com/Azure/azure-data-lake-store-python/blob/82f319fb045286f6cf953ce7510568574af1666a/azure/datalake/store/multithread.py#L199):
`file_pairs = [(os.path.join(self.lpath, os.path.relpath(f['name'] +'.inprogress', local_rel_rpath)), f)`

Specifically, `os.path.join()` shouldn't contain latter arguments that start with a slash (i.e., local_rel_rpath).  If this occurs, the arg is interpreted as an absolute path and overwrites the preceding arguments.
[https://stackoverflow.com/questions/1945920/why-doesnt-os-path-join-work-in-this-case](https://stackoverflow.com/questions/1945920/why-doesnt-os-path-join-work-in-this-case)

**Comment by milanchandna** [comment]
Based on code path and your input I was able to list down some use cases. (see below)
But unable to reproduce the scenario which you are mentioning.
Though I figured out one scenario in which files might be written down in parent folder but that too if you are using a pattern '*' in rpath. (see below)
It will be really helpful if you can drill down your issue a bit and tell me the rpath and lpath values and/or files pattern in remote path, when it is misbehaving, so that I can pin point the issue.

Please refer below the scenarios which I thought of. Again these scenarios are based on your inputs for rpath and lpath. The printed values below will be used as download location of file (after removing .inprogress from end)

###Scenarios with multiple remote files
##-------------
rpath = "/root/path/files"
lpath = "/testpath/test"
local_rel_rpath = "/root/path/files"
remote_file1 = "/root/path/files/foo.txt"
remote_file2 = "/root/path/files/bar/foo.txt"


print(os.path.join(lpath, os.path.relpath(remote_file1+'.inprogress', local_rel_rpath)))
#/testpath/test/foo.txt.inprogress
print(os.path.join(lpath, os.path.relpath(remote_file2+'.inprogress', local_rel_rpath)))
#/testpath/test/bar/foo.txt.inprogress


##-------------
rpath = "/root/path/files*"
lpath = "/testpath/test"
local_rel_rpath = "/root/path/files"
remote_file1 = "/root/path/filesone.txt"
remote_file2 = "/root/path/files/foo.txt"


print(os.path.join(lpath, os.path.relpath(remote_file1+'.inprogress', local_rel_rpath)))
#/testpath/test/../filesone.txt.inprogress
print(os.path.join(lpath, os.path.relpath(remote_file2+'.inprogress', local_rel_rpath)))
#/testpath/test/foo.txt.inprogress


###Scenarios with single remote file
##-------------
rpath = "/root/path/files"
lpath = "/testpath/test"
local_rel_rpath = "/root/path/files"
remote_file = "/root/path/files"

# if lapth exists and is diretcory
print(os.path.join(lpath, os.path.basename(remote_file+'.inprogress')))
#/testpath/test/files.inprogress

# if lpath doesn't exist or is not a directory
print(lpath)
#/testpath/test

##-------------
rpath = "/root/path/files*"
lpath = "/testpath/test"
local_rel_rpath = "/root/path/files"
remote_file = "/root/path/filesone.txt"

# if lapth exists and is diretcory
print(os.path.join(lpath, os.path.basename(remote_file+'.inprogress')))
#/testpath/test/files.inprogress

# if lpath doesn't exist or is not a directory
print(lpath)
#/testpath/test

**Comment by masangster** [comment]
Hi Milan, 

In my testing I have found the following:

1. If my rpath = "/root/testpath/testdir" and is a directory, my lpath = "/testfolder/test", and the script being run is stored in C:/scriptlocation, then the directory being downloaded ends up in "C:/scriptlocation/root/testpath/testdir", so the rpath value is used instead of the lpath. This happens whether or not the lpath target directory actually exists or not. I would expect this would either result in the directory being saved to "C:/scriptlocation/testfolder/test/...." or if it was consistent with the single file download behaviour, to "C:/testfolder/test/....".

2. If my rpath = "/root/testpath/testdir" and is a directory, my lpath = "./testfolder/test" (note the dot at the front), and the script being run is stored in C:/scriptlocation, then the download fails whether or not the lpath target directory exists or not. If this was consistent with the single file download behaviour, it would download to "C:/scriptlocation/testfolder/test/...." given the use of the preceeding dot.

3. If my rpath = "/root/testpath/testdir/file.txt" and is a single file, my lpath = "/testfolder/test" , and the script being run is stored in C:/scriptlocation, then the download ends up being stored at "C:/testfolder/test", but is not actually file.txt, but a file with unknown extension called test. This is obviously a symptom of specifying a directory for the lpath and a single file for the rpath, but it is still concerning that the local path is no longer used relative to the script location, and the file is downloaded to "C:<lpath>" instead of "C:/scriptlocation/<lpath>", as I would expect that either the download fails or at least is still respecting the relative path from the script location rather than from C:. 

4. If my rpath = "/root/testpath/testdir/file.txt" and is a single file, my lpath = "./testfolder/test" (note the dot in front) , and the script being run is stored in C:/scriptlocation, then the download ends up being stored at "C:/scriptlocation/testfolder/test", but again is not actually file.txt, but a file with unknown extension called test. This is again obviously a symptom of specifying a directory for the lpath and a single file for the rpath, and in this case at least the lpath is respected relative to the script location, but this is different behaviour to when downloading a directory instead of a single file (ie. using a dot in front fails every time for directory downloads). 

5. If my rpath = "/root/testpath/testdir/file.txt" and is a single file, my lpath = "./testfolder/test/file.txt" (note the dot in front) , and the script being run is stored in C:/scriptlocation, then the download ends up being stored at "C:/scriptlocation/testfolder/test", and is actually file.txt as expected. This works if the target directory is already in existence or not.

6. If my rpath = "/root/testpath/testdir/file.txt" and is a single file, my lpath = "/testfolder/test/file.txt" (note the dot in front) , and the script being run is stored in C:/scriptlocation, then the download ends up being stored at "C:/testfolder/test", and is actually file.txt. This works if the target directory is already in existence or not, but is also inconsistent with the directory download version. 

So overall the downloading on a single file works relatively as expected, but the downloading of a directory does not. As it stands, as highlighted in 1, there is no way to download to the intended folder, whether relative to the script location or an absolute file path is provided.

**Comment by milanchandna** [comment]
@masangster, Thanks for detailed info, I found the bug.
The issue is when lpath is Unix based path (starting with /) and current OS is Windows (paths starting with C:\)

So in your scenarios, point 3,4,5,6 are behaving as per expectation and is the right behavior.
1,2 should have behaved in similar manner.
When you start the lpath with "/" the download will start from the root directory followed by lpath. In windows root with "/" is the current directory's drive letter. So in point 1, directories should be saved in C:/testfolder/test/
And when you start the lpath with "./" then download will start from current directory followed by lpath. So in point 2 the directories should be saved in C:/scriptlocation/testfolder/test/

Working on the fix.

**Comment by masangster** [comment]
Thanks @milanchandna  - let me know if you need someone to test when implemented :)

**Comment by milanchandna** [comment]
This has been fixed in version 0.0.23, closing this issue.
https://pypi.python.org/pypi/azure-datalake-store/0.0.23 

@masangster can you please verify from your end.

**Comment by masangster** [comment]
@milanchandna I can confirm this now works as expected - thanks very much! I did however post another issue at the same time as this one (#214 ) that still does not work as intended. Are there plans to fix this as well? Basically the issue is that when a multi level directory is downloaded but only one subfolder has a file in it, the directory structure is not preserved and the file is not reliably downloaded.
